import type { Metadata } from "next";
import { Inter } from "next/font/google";

import "./globals.css";
import Providers from "@/components/Providers";
const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});
export const metadata: Metadata = {
  title: "CineVerse",
  description: "Generated by create next app",
};   
export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
   

    <html
      lang="en"
      suppressHydrationWarning
      className={`${inter.variable} h-full antialiased scroll-smooth `}
      >
      <body className={`${inter.className} min-h-full flex flex-col`} >
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
    
  );
}
